### PR TITLE
linagora/customers#80 redirect to login when the silent renew has failed

### PR DESCRIPTION
**Pull request by rezk2ll**
related to https://github.com/linagora/customers/issues/80
- most common error: `invalid_grant`

### CODE REVIEW

**Comment by tanandy** [comment]
its a draft ?

**Comment by rezk2ll** [comment]
> its a draft ?

I just wanted to have everybody else's opinion ( and it's a draft so that no one does a hasty merge )

**Comment by tanandy** [comment]
if its a one shot redirection to login im ok. if not and close to a loop im not.

Login here means CAS automatic login (it depends on the use case and the IDP flow)

**Comment by rezk2ll** [comment]
> if its a one shot redirection to login im ok. if not and close to a loop im not.
> 
> Login here means CAS automatic login (it depends on the use case and the IDP flow)

it doesn't loop, when the client fails to refresh the token he is redirected to the login

**Review by tanandy — APPROVED** [review]

**Review by renaudboyer — APPROVED** [review]

**Review by tuanlc — APPROVED** [review]

**Pull request merged**
