### PR TITLE
OpenPaaS-Suite/esn-frontend-calendar#218 Add block farLeft to subheader

### LINKED ISSUE #218: [STORY] Hide the calendar sidebar
#### Definition

As a user, I want to hide the calendar sidebar to have the agenda full screen.

#### Criteria

- [x] There should be a button to toggle the sidebar on the left side of the subheader with the menu icon (`mdi-menu`).
- [x] When clicking on the icon and the sidebar is currently shown, the sidebar should be hidden and the agenda view expands to occupy the full width of the screen.
- [x] When clicking on the icon and the sidebar is currently hidden, the sidebar should be shown.
- [ ] When hovering over the icon, there should be a hover effect and a tooltip - "Toggle sidebar".
- [ ] (Optional) There should be a smooth animation transition when toggling the sidebar.

#### UI/UX Design

- The default view (the sidebar is shown):

toggle-sidebar-design-1

- The sidebar is hidden:

toggle-sidebar-design-2

### PR DESCRIPTION
**Pull request by pbson**
Resolves https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/218.

### CODE REVIEW

**Review by itswillta — DISMISSED** [review]

**Comment by itswillta** [comment]
There is 1 weird commit:

image

You should rebase your branch from `main`, not merge.

**Comment by pbson** [comment]
> There is 1 weird commit:
> 
> image

This branch is out of date, so that's the commit to update it from Github. Should I make the change to the commit message ?

**Comment by itswillta** [comment]
> > There is 1 weird commit:
> > image
> 
> This branch is out of date, so that's the commit to update it from Github. Should I make the change to the commit message ?

The commit shouldn't exist. There should only be one commit here.

What you need to do is delete the merge commit, and then make sure you're on the `esn-cal#218` branch, and run the following command:

```
git rebase main
```

**Review by rezk2ll — DISMISSED** [review]

**Review by rezk2ll — DISMISSED** [review]

**Comment by itswillta** [comment]
The commits are still wrong. I think we can use https://github.com/OpenPaaS-Suite/esn-frontend-common-libs/pull/157 instead.

**Comment by rezk2ll** [comment]
> The commits are still wrong. I think we can use #157 instead.

the commits are ok, i just clicked on the `update branch` button to not dismiss approvals.

**Review by itswillta — APPROVED** [review]

**Pull request merged**
