### PR TITLE
Wait for token to boostrap session

### PR DESCRIPTION
**Pull request by alagane**
The user API need authentication.
Then the first request to user API on mailto will not fail and it will
load correctly.

Related to https://github.com/linagora/customers/issues/55

### CODE REVIEW

**Comment by tanandy** [comment]
please squash the pr when reviewed

**Comment by tanandy** [comment]
tests are failing

**Comment by alagane** [comment]
> tests are failing

The last commit should fix tests.

**Review by oubchid — APPROVED** [review]

**Comment by rezk2ll** [comment]
squash'em

**Comment by alagane** [comment]
> squash'em

We can squash'em when merging no? I took the habit to make fixup commits so the review is easier.
I do not know the best solution for this problem.

**Comment by rezk2ll** [comment]
> > squash'em
> 
> We can squash'em when merging no? I took the habit to make fixup commits so the review is easier.
> I do not know the best solution for this problem.

GitHub doesn't support the option to squash when merging like GitLab.
for the review part when the PR is fine we can squash and to not lose approvals by committing again we can ask @tanandy to change the settings to disable the `Dismiss stale pull request approvals when new commits are pushed` like this:

image

**Review by rezk2ll — APPROVED** [review]

**Comment by alagane** [comment]
> > > squash'em
> > 
> > 
> > We can squash'em when merging no? I took the habit to make fixup commits so the review is easier.
> > I do not know the best solution for this problem.
> 
> GitHub doesn't support the option to squash when merging like GitLab.
> for the review part when the PR is fine we can squash and to not lose approvals by committing again we can ask @tanandy to change the settings to disable the `Dismiss stale pull request approvals when new commits are pushed` like this:

Isn't this button ok? 
image

**Comment by tanandy** [comment]
> > > > squash'em
> > > 
> > > 
> > > We can squash'em when merging no? I took the habit to make fixup commits so the review is easier.
> > > I do not know the best solution for this problem.
> > 
> > 
> > GitHub doesn't support the option to squash when merging like GitLab.
> > for the review part when the PR is fine we can squash and to not lose approvals by committing again we can ask @tanandy to change the settings to disable the `Dismiss stale pull request approvals when new commits are pushed` like this:
> 
> Isn't this button ok?
> image

yes it is exactly what i mean by squash :)

**Comment by rezk2ll** [comment]
> > > > squash'em
> > > 
> > > 
> > > We can squash'em when merging no? I took the habit to make fixup commits so the review is easier.
> > > I do not know the best solution for this problem.
> > 
> > 
> > GitHub doesn't support the option to squash when merging like GitLab.
> > for the review part when the PR is fine we can squash and to not lose approvals by committing again we can ask @tanandy to change the settings to disable the `Dismiss stale pull request approvals when new commits are pushed` like this:
> 
> Isn't this button ok?
> image

oops

**Pull request merged**
